### PR TITLE
Fix AdoptedResource functionality for firewall

### PR DESCRIPTION
**Pull request by nnbu**
Issue #: aws-controllers-k8s/community#1947

Description of changes:

RCA:

Following CR currently fails to adopt the existing firewall resource.
```
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: fw1
spec:
  aws:
    nameOrID: myfw1
  kubernetes:
    group: networkfirewall.services.k8s.aws
    kind: Firewall
    metadata:
      name: fw-adopted
      namespace: default
```
The error comes from https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/adoption_reconciler.go#L157

Solution:
`sdkFind()` needs to update the spec with all the `required` values of the CRs to avoid this error.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nnbu** [comment]
@a-hilaly The repo does not have e2e tests. Hence the failure.

**Comment by nnbu** [comment]
@a-hilaly Added the testcases as suggested. Tests are passing.

**Comment by a-hilaly** [comment]
@nnbu Can we make a 0.0.1 release?

**Review by a-hilaly — APPROVED** [review]
Thank you @nnbu 
/lgtm

**Comment by nnbu** [comment]
Hi @a-hilaly 
I created https://github.com/aws-controllers-k8s/networkfirewall-controller/pull/17 for 0.0.1 release.
It needs to be merged after this PR is merged.

The current one is failing with a newly added test, I think. Could you help on this?

**Review by a-hilaly — APPROVED** [review]
@nnbu I just pushed to you branch - looks like we had a copy of `main.go` in the root directory.
it should be fixed now.
/lgtm

**Comment by nnbu** [comment]
I think, @a-hilaly is `assignee` , so your approval is not taken into account. Let me change the assignee to myself

**Comment by a-hilaly** [comment]
@nnbu I think our prow infra was missing few permissions, giving it a another show now

**Pull request merged**
